### ISSUE TITLE
ipccar5/glaciers fails at postprocess step when run within EnTK

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#106]
The task folder is having difficulty copying input files to the right space. When fails, ls looks as:

```
ar5_glaciers_postprocess_data.tgz  AssignFP.py         read_locationfile.py
ar5_postprocess_glaciers.py        ReadFingerprint.py
```

Missing are files specified by copy_input_data:

```
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_data.pkl"
          - "%PIPELINE_ID%_projections.pkl"
```

Having trouble figuring out why.
