### ISSUE TITLE
Tlm_sterodynamics should allow non-standard scenario labels

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#275]
Because the DSL projection requires use of a SSP to control the correlation between thermal expansion and DSL, the module will likely choke if given a different scenario label. Should add option to specify the scenario for DSL correlation separately from the scenario for OHC

**Comment by bobkopp** [comment]
I took a first pass at this in the `scenario_dsl` branch. This has not been tested. Tests should be:

1. Ensuring a standard run reproduces prior DSL for NYC under two different SSP scenarios
2. Using a custom scenario with a non-SSP name (this should break, because the DSL correlation will not be found)
3. Repeating the above, but with`scenario_dsl: ssp245`

**Comment by bobkopp** [comment]
@JMGilbert could you give this a spin with the RFFSPs?

**Comment by bobkopp** [comment]
The branch modifies tlm/sterodynamics. It will need to be reconciled with the global_only branch. @AlexReedy

**Comment by bobkopp** [comment]
Goal for v1.1.2 is to have experimental functionality in place without breaking anything. Tests 2-3 can await version 1.1.3.

**Comment by AlexReedy** [comment]
The feature has been added to our global_only dev branch for 1.1.2 and we can run tlm (full and global only) without breaking the module. I have pinged @JMGilbert on slack about doing one of his non standard scenario runs to confirm as I don't have any non standard scenario data.

**Comment by bobkopp** [comment]
Great! Bumping issue to v1.1.3 for testing.

**Comment by JMGilbert** [comment]
I tested a workflow 1f/2f setup with `climate.nc4` data using the dummy module where the group is "rff" and the scenario in the config is "rff" and it worked great. Let me know if you have any other tests/if I interpreted the way this was to be tested correctly.

**Comment by bobkopp** [comment]
@JMGilbert Can you post your config.yml file? And also, did you run NYC projections as well as global?

**Comment by JMGilbert** [comment]
I just tried global, will try the NYC projections now.

<details>
<summary> config.yml </summary>

```
global-options:
    nsamps: 10000
    scenario: rff
    pyear_start: 2020
    pyear_end: 2300
    pyear_step: 1
    baseyear: 2005
    pipeline_file: 'pipeline.global.yml'


climate_step:
    dummy:
        module_set: "facts"
        module: "dummy"
        pipeline_file: 'pipeline.yml'
        input_data_file:
            - "ohc.nc4"
            - "gsat.nc4"
            - "climate.nc4"
        climate_output_data:
            - "ohc.nc4"
            - "gsat.nc4"
            - "climate.nc4"
        generates_climate_output: true

sealevel_step:
    GrIS1f:
        module_set: "FittedISMIP"
        module: "GrIS"
        options:
            crateyear_start: 2080
            crateyear_end: 2100
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    larmip:
        module_set: "larmip"
        module: "AIS"
        options_allowoverwrite:
           climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf2f"

    ar5glaciers:
        module_set: "ipccar5"
        module: "glaciers"
        options:
            gmip: 2
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    ar5AIS:
        module_set: "ipccar5"
        module: "icesheets"
        pipeline_file: "pipeline.AIS.global.yml"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"

    ocean:
        module_set: "tlm"
        module: "sterodynamics"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    lws:
        module_set: "ssp"
        module: "landwaterstorage"
        options:
            scenario: "ssp5"
            dcrate_lo: -0.4
        include_in_workflow:
            - "wf1f"
            - "wf2f"

totaling_step:
    total:
        module_set: "facts"
        module: "total"
        loop_over_workflows: true
        loop_over_scales: true
        stages:
            - workflow
```
</details>
